### ISSUE TITLE
Zádání

### ISSUE THREAD

**Issue by brona-ruzicka** [dobbyasas/pivovar#1]
Rád bych si zkusil tuhle problematiku taky vyřešit.
Nemáš ještě někde nějaké plnější znění zadání, abych se na to taky mohl podívat.

Díky moc
Broňa

**Comment by dobbyasas** [comment]
propomeň mi to někdy zítra, najdu to

**Comment by dobbyasas** [comment]
čau hele promiň že to tak extrémně dlouho trvalo ale zapomněl jsem na to a našel to tu až teď XD

here you go, have fun:

Pivovar

Pivovar „Chmelovar“ zásobuje pivem všechny hospody vzdálené méně než 100
km. Pivovar je to výkonný, takže zvládne vyrobit piva dostatek. Hospod je celkem 500. Pro
efektivnější distribuci piva si pivovar vybudoval na tomto území 4 překladiště. Pivo je
z pivovaru nejdříve rozvezeno do těchto překladišť. Z každé hospody vede přímá cesta do
všech překladišť a do 10 nejbližších/všech hospod. Kamion jezdí průměrnou rychlostí 80
km/h a uveze maximálně 50 sudů piva. Na každé překladiště se v jeden okamžik vejde
maximálně 600 sudů. Každá hospoda spotřebuje denně 1-6 sudů piva. Dobu pro
naložení/vyložení sudu, tankování a přestávky řidičů zanedbáme. Pivo je nutné doručit vždy
do 24 hodin od objednávky. Hospody posílají objednávky vždy v celou hodinu a to od 10:00
až 17:00. Rozvoz piva probíhá rovněž od 10:00 do 17:00. Počet kamionů není omezen.
Hlavním cílem je simulovat a řídit provoz zásobování hospod, tak, aby každé
hospodě dorazilo pivo do 24 hodin. Pozici překladišť si vhodně zvol a hospody si rovnoměrně
vygeneruj tak, aby pod každé překladiště spadalo 100 hospod.
